# NumPy

## Array Basics

In [1]:
import numpy as np

In [2]:
import numpy

### list ==> np array

In [4]:
np.array((1, 2, 3))

array([1, 2, 3])

In [9]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [11]:
type(arr)

numpy.ndarray

In [14]:
print(arr.mean())

2.5


In [17]:
arr_mean = np.mean(arr)
arr_mean

np.float64(2.5)

In [18]:
print(arr_mean)

2.5


In [19]:
num_list = [ 1, 2.3, 3, 4, 5]

In [20]:
type(num_list)

list

In [21]:
arr = np.array(num_list)

In [23]:
type(arr)

numpy.ndarray

In [24]:
arr.dtype


dtype('float64')

### arange() ==> array

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(0, 100, 10)   ### start stop step

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
list_2d = [
    [1, 2, 3], 
    [4, 5, 6]
]

In [30]:
list_2d

[[1, 2, 3], [4, 5, 6]]

In [33]:
list_3d = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [11, 2, 3],
        [14, 5, 6]
    ]
]
list_3d

[[[1, 2, 3], [4, 5, 6]], [[11, 2, 3], [14, 5, 6]]]

In [34]:
np.array(list_2d)

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.array(list_3d)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11,  2,  3],
        [14,  5,  6]]])

In [36]:
nums = [ 1, 2, 3, 4, ] 
[ num**3 for num in nums ]

[1, 8, 27, 64]

In [37]:
nums = [ num for num in [1, 2, 3 , 4, 5] ]

In [38]:
nums

[1, 2, 3, 4, 5]

In [39]:
nums2 = [ num**2 for num in [1, 2, 3 , 4, 5] ]
nums2

[1, 4, 9, 16, 25]

In [40]:
nums_if = [ num**2 for num in nums if num % 2 == 0 ]
nums_if

[4, 16]

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.zeros(2, 3)

TypeError: Cannot interpret '3' as a data type

In [46]:
prices = np.array([10, 12, 15])
quantities = np.array([4, 3, 2])
revenue = prices * quantities

revenue

array([40, 36, 30])