# NumPy

## Array Basics

In [1]:
import numpy as np

In [2]:
import numpy

In [47]:
%pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


### list ==> np array

In [55]:
np.array([(1,  3), [ 1, 3]])

array([[1, 3],
       [1, 3]])

In [9]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [11]:
type(arr)

numpy.ndarray

In [14]:
print(arr.mean())

2.5


In [17]:
arr_mean = np.mean(arr)
arr_mean

np.float64(2.5)

In [18]:
print(arr_mean)

2.5


In [12]:
nums = [ 1, 2.3, "3", 4, 5]
for num in nums:
    print(num, end= " ")

1 2.3 3 4 5 

In [2]:
old = 67
while True:
    age = int(input("what is your age? "))
    if age > old:
        print("retire")
        break
    

what is your age?  21
what is your age?  22
what is your age?  66
what is your age?  67
what is your age?  68


retire


In [6]:
nums2 = [
    [ 1, 2, 3],
   [4, 5, 6 ]
    
]
nums2


[[1, 2, 3], [4, 5, 6]]

## Functions

In [8]:
### no params, nno return

def test( ):
    print("helloooooo")
test()

helloooooo


In [16]:
### with params & returns

def test(num1, num2):
    # total = num1 + num2    
    # return total
    return( num1 + num2 )

# t = test(1, 2)
test(1, 2)
# print("the total: ", t)

3

In [24]:
%pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [25]:
import numpy as np

In [ ]:
np.

In [23]:
d = { "a": [0, 0, 0], "b": [1, 2, 3] }
d

{'a': [0, 0, 0], 'b': [1, 2, 3]}

In [10]:
nums[0]
nums2[0][5]

IndexError: list index out of range

In [23]:
type(arr)

numpy.ndarray

In [24]:
arr.dtype


dtype('float64')

### arange() ==> array

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(0, 100, 10)   ### start stop step

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
list_2d = [
    [1, 2, 3], 
    [4, 5, 6]
]

In [30]:
list_2d

[[1, 2, 3], [4, 5, 6]]

In [33]:
list_3d = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [11, 2, 3],
        [14, 5, 6]
    ]
]
list_3d

[[[1, 2, 3], [4, 5, 6]], [[11, 2, 3], [14, 5, 6]]]

In [34]:
np.array(list_2d)

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.array(list_3d)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11,  2,  3],
        [14,  5,  6]]])

In [36]:
nums = [ 1, 2, 3, 4, ] 
[ num**3 for num in nums ]

[1, 8, 27, 64]

In [37]:
nums = [ num for num in [1, 2, 3 , 4, 5] ]

In [38]:
nums

[1, 2, 3, 4, 5]

In [39]:
nums2 = [ num**2 for num in [1, 2, 3 , 4, 5] ]
nums2

[1, 4, 9, 16, 25]

In [40]:
nums_if = [ num**2 for num in nums if num % 2 == 0 ]
nums_if

[4, 16]

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.zeros(2, 3)

TypeError: Cannot interpret '3' as a data type

In [46]:
prices = np.array([10, 12, 15])
quantities = np.array([4, 3, 2])
revenue = prices * quantities

revenue

array([40, 36, 30])