In [45]:
import numpy as np
import datascience
from datascience import util

In [46]:
### learn what functions are available in numpy
### create an array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [47]:
### assign the created array to a variable called nums


In [48]:
### the make_array function in datascience.util:

util.make_array(1, 2, 3, 4, 5)

array([1, 2, 3, 4, 5])

In [49]:
### 5.1 create a string array
english_parts_of_speech = util.make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'],
      dtype='<U12')

In [53]:
### 5.1 create an array of double
baseline_high = 14.48
highs = util.make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [51]:
### 5.1 arithmetic operation / operators
(9/5) * highs + 32

array([ 56.48  ,  57.8966,  58.253 ,  59.2952])

In [52]:
### 5.1 array functions: size, sum, mean of highs

*** Please replay this part with your answers ***


SyntaxError: invalid syntax (4072016412.py, line 3)

In [ ]:
### 5.1.1 more array functions
### diff

np.diff(highs)


Q: What does the diff() function do?`

In [ ]:
A: *** answer here ***

In [ ]:
### functions takes an array as an argument and returns a single value
np.sum(highs) 



In [ ]:
### functions takes an array as an argument and returns an array of values
np.sqrt(highs)

In [ ]:
### functions takes an array of strings and returns an array
# *** use the english_parts_of_speech variable to perform a count here. ***
# hint: np.char.count(english_parts_of_speech, 'noun')