# Homework 2: Arrays and Tables

## 0. Using Jupyter Notebook

#### The Workflow
1. **Go into your project folder**: Use a **terminal** (PowerShell for Windows and Terminal.app for macOS) & move (**cd**) into your project directory (*USERNAME*/**workspace/introdsm**)
   1. The lab computers can be inconsistent in the virtual environment and package installation.
   2. Bring your own device (BYOD) is strongly encouraged. 
2. **Activate the virtual environment**:
   1. For macOS, Enter "**source .venv/bin/activate**" 
   2. For Windows, Enter "**.venv\Scripts\activate**" 
   3. You should see the ".venv" prefix at your terminal prompt when the virtual environment is activated.
3. **Launch Jupyter Notebook** by entering "jupyter notebook".
4. Work on your Notebook.
5. **Shut down Jupyter Notebook** by selecting the File menu => Shut Down.
6. **Deactivate the virtual environment**: At your terminal, enter "**deactivate**".

#### Installing packages: otter-grader & datascience
1. Ideally, you should install packages using a terminal:
   1. In a terminal, activate your virtual environment.
   2. Enter "pip install *PACKAGE_NAME*" to install the package/module/ibrary. 
2. To install packages from Jupyter Notebook, for example:
   1. Enter **```%pip install datascience```** (this will take a while, like 2 minutes)
   2. Enter **```%pip install otter-grader```**. 
3. **Comment out** the installation line after installation is complete. 

In [1]:
########## Install required modules here datascience, otter-grade ##### 
########## You may uncomment and run the following installatio one-by-one
# %pip install datascience
# %pip install otter-grader
########## Remove or comment out (using #) the installation commands after done #####
########## You may see many lines when installing
########## When installation is done, you will see a message at the very end of the lines: "Note: you may need to restart the kernel to use updated packages."
########## Go to Kernal ==> Restart Kernal and Clear Outputs of All Cells

**Attention:**
1. Otter grader notes:
    1. Provide your answers in the **designated spaces**.
    2. **Do not re-assign variables** in the notebooks! For example, if you use `max_temperature` in your answer to one question, do not reassign it later on. Otherwise, you will fail tests that you thought you were passing previously!
    3. Most "tests" in this homework **test formats and data types** of your answer, not their **correctness**. When you see you are **100% passed**, it **doesn't mean your final grade will be 100%**.
2. Points may be scaled in Canvas assignment grade. 
3. Teamwork and academic honesty:
    1. Academic honor is important. **DO NOT cheat.**
    2. Discussing problems with others is encouraged, but directly sharing your answers/files is **NOT**.
    3. Use of AI as a learning tool is encouraged, but do not do copy-n-paste. 
4. Time management and get help:
    1. Start early so that you have time to get help if you're stuck.
    2. Come to the TA's help sessions and the instructors office hours for help.

**Helpful Resource:**
- [Python Reference](http://data8.org/sp24/reference/): Cheat sheet of helpful array & table methods used in Data 8!

**Recommended Readings:**
- [Arrays](https://introdsm.org/chapters/05/1/Arrays.html) 
- [Tables](https://introdsm.org/chapters/06/Tables.html)
- [Programming in Python](http://introdsm.org/chapters/03/programming-in-python.html)

In [2]:
# Initialize Otter Grader
import otter
grader = otter.Notebook("hw02.ipynb")

In [3]:
# Run this cell and ignore the output. It is checking to see if you ran the first cell! 
# If you get a NameError, please run the cell at the very TOP of this notebook!

grader

## 1. Creating Arrays

In [4]:
# Run this cell to set up the notebook, but please don't change it.

import numpy as np
from datascience import *
import warnings
warnings.simplefilter('ignore', FutureWarning)

**Question 1.** Make an array called `weird_numbers` containing the following numbers (in the given order) **(4 Points)**:

1. -2
2. the floor of 17.6
3. 3
4. 5 to the power of the ceil of 5.3

*Hint:* `floor` and `ceil` are functions in the `math` module. Importing modules is covered in Lab 2!

*Note:* Python lists are different/behave differently than NumPy arrays. In Data 8, we use NumPy arrays, so please make an **array**, not a Python list.


In [5]:
# This is question 1. Our solution involved one extra line of code before creating weird_numbers. 
# Use math.ceil and math.floor. You have to import math here first
# When you do make_array, enclose the elements individually; do not create a list. grader does not like it. 
import math
weird_numbers = make_array(-2, math.floor(17.6), 3, 5**math.ceil(5.3))
weird_numbers

array([   -2,    17,     3, 15625])

In [6]:
### check the type of the variable
type(weird_numbers)
### datascience.util uses numpy to create numpy arrays (n-dimensinal arrays == ndarray)
### nd = n-dimensional 

numpy.ndarray

In [7]:
grader.check("q1_1")

q1_1 results: All test cases passed!

**Question 2.** Make an array called `book_title_words` containing the following three strings: "Eats", "Shoots", and "and Leaves". **(4 Points)**


In [8]:
book_title_words = make_array("Eats", "Shoots", "and Leaves")
book_title_words

array(['Eats', 'Shoots', 'and Leaves'],
      dtype='<U10')

In [9]:
grader.check("q1_2")

q1_2 results: All test cases passed!

Strings have a method called `join`.  `join` takes one argument, an array of strings.  It returns a single string.  Specifically, the value of `a_string.join(an_array)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `an_array`, **except** `a_string` is inserted in between each string.

**Question 3.** Use the array `book_title_words` and the method `join` to make two strings **(4 Points)**:

1. "Eats, Shoots, and Leaves" (call this one `with_commas`)   ### not the space after the commas
2. "Eats Shoots and Leaves" (call this one `without_commas`)

*Hint:* If you're not sure what `join` does, first try just calling, for example, `"data8".join(book_title_words)` .


In [10]:
with_commas = ", ".join(book_title_words)
without_commas = " ".join(book_title_words)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats, Shoots, and Leaves
without_commas: Eats Shoots and Leaves


In [11]:
grader.check("q1_3")

q1_3 results: All test cases passed!

## 2. Indexing Arrays

These exercises give you practice accessing individual elements of arrays. In Python (and in many programming languages), each element is accessed by its *index*; for example, the first element is the element at index 0. Indices must be **integers**. ### use square brackets

Be sure to refer to the [Python Reference](http://data8.org/sp25/reference/) on the website if you feel stuck!

**Question 1.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`. **(4 Points)**


In [12]:
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = some_numbers[2]
third_element

-6

In [13]:
grader.check("q2_1")

q2_1 results: All test cases passed!

**Question 2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information (the cells that say "Ellipsis") by assigning `blank_a`, `blank_b`, `blank_c`, and `blank_d` to the correct elements in the table. **(4 Points)**

*Hint:* Replace the `...` with strings or numbers. As a reminder, indices should be **integers**.


In [14]:
blank_a = "third"
blank_b = "fourth"
blank_c = 0
blank_d = 3
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", blank_a, blank_b, "fifth"),
    "Index",                     make_array(blank_c, 1, 2, blank_d, 4),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
third                     | 2     | -6
fourth                    | 3     | -10
fifth                     | 4     | -15

In [15]:
grader.check("q2_2")

q2_2 results: All test cases passed!

**Question 3.** You'll sometimes want to find the **last** element of an array. Suppose an array has 142 elements. What is the index of its last element? **(4 Points)**

*Note:* Your answer must be a positive number.


In [16]:
index_of_last_element = 141

In [17]:
grader.check("q2_3")

q2_3 results: All test cases passed!

More often, you don't know the number of elements in an array (its *length*). (For example, it might be a large dataset you found on the Internet.) The function `len` takes a single argument, an array, and returns an integer that represents the `len`gth of that array.

**Question 4.** The cell below loads an array called `president_birth_years`. Calling `tbl.column(...)` on a table returns an array of the column specified, in this case the `Birth Year` column of the `president_births` table. The last element in that array is the most recent among the birth years of all the deceased Presidents. Assign that year to `most_recent_birth_year`. **(4 Points)**

**Note:** Avoid Googling the answer. You should be able to answer this question only using table methods.

In [18]:
president_birth_years = Table.read_table("president_births.csv").column('Birth Year')

most_recent_birth_year = president_birth_years[-1]
most_recent_birth_year

1917

In [19]:
grader.check("q2_4")

q2_4 results: All test cases passed!

**Question 5.** Finally, assign `min_of_birth_years` to the minimum of the first, sixteenth, and last birth years listed in `president_birth_years`. **(4 Points)**

**Note:** Use the Python `min` function and table methods to find the answer. Avoid manually calculating the result yourself!

In [20]:
min_of_birth_years = min(president_birth_years[0], president_birth_years[15], president_birth_years[-1])
min_of_birth_years

1732

In [21]:
grader.check("q2_5")

q2_5 results: All test cases passed!

## 3. Basic Array Arithmetic

**Question 1.** Multiply the numbers 42, -4224, 424224242, and 250 by 157. Assign each variable below such that `first_product` is assigned to the result of $42 * 157$, `second_product` is assigned to the result of $-4224 * 157$, and so on. **(4 Points)**

*Note*: For this question, **don't** use arrays.


In [22]:
first_product = 42 * 157
second_product = -4224 * 157
third_product = 424224242 * 157
fourth_product = 250 * 157
print("First Product:", first_product)
print("Second Product:", second_product)
print("Third Product:", third_product)
print("Fourth Product:", fourth_product)

First Product: 6594
Second Product: -663168
Third Product: 66603205994
Fourth Product: 39250


In [23]:
grader.check("q3_1")

q3_1 results: All test cases passed!

**Question 2.** Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator. Store the 4 results in an array named `products`. **(4 Points)**

In [24]:
### use the make_array() function?
numbers = make_array(42, -4224, 424224242, 250)
products = numbers * 157
products

array([       6594,     -663168, 66603205994,       39250])

In [25]:
grader.check("q3_2")

q3_2 results: All test cases passed!

**Question 3.** Oops, we made a typo! Instead of 157, we wanted to multiply each number by 1577.  Compute the correct products in the cell below using array arithmetic. Notice that your job is really easy if you previously defined an array containing the 4 numbers. **(4 Points)**


In [26]:
correct_products = numbers * 1577
correct_products

array([       66234,     -6661248, 669001629634,       394250])

In [27]:
grader.check("q3_3")

q3_3 results: All test cases passed!

**Question 4.** We've loaded an array of temperatures in the next cell.  Each number is the highest temperature observed on a day at a climate observation station, mostly from the US.  Since they're from the US government agency [NOAA](https://www.noaa.gov/), all the temperatures are in Fahrenheit.

Convert all the temperatures to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$, i.e. $C = (F - 32) * \frac{5}{9}$. After converting the temperatures to Celsius, make sure to **ROUND** the final result  to the nearest integer using the `np.round` function. **(4 Points)**


In [28]:
max_temperatures = Table.read_table("temperatures.csv").column("Daily Max Temperature")
# Table.read_table("temperatures.csv")
# max_temperatures

max_temperatures_celsius = (max_temperatures-32) * (5/9)
celsius_temps_rounded = np.round(max_temperatures_celsius)
celsius_temps_rounded

array([ -4.,  31.,  32., ...,  17.,  23.,  16.])

In [29]:
grader.check("q3_4")

q3_4 results: All test cases passed!

**Question 5.** The cell below loads all the *lowest* temperatures from each day (in Fahrenheit).  Compute the daily temperature range for each day. That is, compute the difference between each daily maximum temperature and the corresponding daily minimum temperature.  **Pay attention to the units and give your answer in Celsius!** <span style="color:red">Make sure **NOT** to round your answer for this question!</span> **(4 Points)**

*Hint:* Use `min_temperatures` and/or `max_temperatures`, and be careful with when you perform your unit conversions. Write out the mathematical computation by hand if you're stuck!
Hint: separate the conversions


In [30]:
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")

celsius_temperature_ranges = max_temperatures_celsius - ((min_temperatures-32) * (5/9))
celsius_temperature_ranges

array([  6.66666667,  10.        ,  12.22222222, ...,  17.22222222,
        11.66666667,  11.11111111])

In [31]:
grader.check("q3_5")

q3_5 results: All test cases passed!

## 4. Old Faithful

Old Faithful is a geyser in Yellowstone that erupts every 44 to 125 minutes (according to [Wikipedia](https://en.wikipedia.org/wiki/Old_Faithful)). People are [often told that the geyser erupts every hour](http://yellowstone.net/geysers/old-faithful/), but in fact the waiting time between eruptions is more variable. Let's take a look.

**Question 1.** The first line below assigns `waiting_times` to an array of 272 consecutive waiting times between eruptions, taken from a classic 1938 dataset. Assign the names `shortest`, `longest`, and `average` so that the `print` statement is correct. **(4 Points)**


In [32]:
waiting_times = Table.read_table('old_faithful.csv').column('waiting')

shortest = min(waiting_times)
longest = max(waiting_times)
average = np.mean(waiting_times)

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 43 to 96 minutes and every 70.8970588235 minutes on average.


In [33]:
grader.check("q4_1")

q4_1 results: All test cases passed!

**Question 2.** Assign `biggest_decrease` to the biggest decrease in waiting time between two consecutive eruptions. For example, the third eruption occurred after 74 minutes and the fourth after 62 minutes, so the decrease in waiting time was 74 - 62 = 12 minutes. **(4 Points)**

*Hint*: We want to return the absolute value of the biggest decrease.

*Note*: `np.diff()` calculates the difference between subsequent values in an array. For example, calling `np.diff()` on the array `make_array(1, 8, 3, 5)` evaluates to `array([8 - 1, 3 - 8, 5 - 3])`, or `array([7, -5, 2])`.


In [34]:
# np.diff() calculates the difference between subsequent values  
# in a NumPy array.
differences = np.diff(waiting_times)
biggest_decrease = abs(min(differences))
biggest_decrease

45

In [35]:
grader.check("q4_2")

q4_2 results: All test cases passed!

**Question 3.** The `faithful_with_eruption_nums` table contains two columns: `eruption_number`, which represents the number of that eruption, and `waiting`, which represents the time spent waiting after that eruption. For example, take the first two rows of the table:

| eruption number | waiting |
|-----------------|---------|
| 1               | 79      |
| 2               | 54      |

We can read this as follows: after the first eruption, we waited 79 minutes for the second eruption. Then, after the second eruption, we waited 54 minutes for the third eruption.

Suppose Oscar and Wendy started watching Old Faithful at the start of the first eruption. Assume that they watch until the end of the tenth eruption. For some of that time they will be watching eruptions, and for the rest of the time they will be waiting for Old Faithful to erupt. How many minutes will they spend waiting for eruptions? **(4 Points)**

*Hint #1:* You can start by using the `take` method on the table `faithful_with_eruption_nums`. 

*Hint #2:* `first_nine_waiting_times` must be an array.


In [36]:
# The following two lines load in our faithful_with_eruption_nums table
faithful = Table.read_table('old_faithful.csv').drop("eruptions")
faithful_with_eruption_nums = faithful.with_column("eruption number", np.arange(faithful.num_rows) + 1).select(1, 0)

first_nine_waiting_times = faithful_with_eruption_nums.take([0, 1, 2, 3, 4, 5, 6, 7, 8]).column("waiting")
total_waiting_time_until_tenth = sum(first_nine_waiting_times)
total_waiting_time_until_tenth

633

In [37]:
grader.check("q4_3")

q4_3 results: All test cases passed!

**Question 4.** Let’s imagine your guess for the next waiting time was always just the length of the previous waiting time. If you always guessed the previous waiting time, how big would your error in guessing the waiting times be, on average? **(4 Points)**

For example, since the first four waiting times are 79, 54, 74, and 62, the average difference between your guess and the actual time for just the second, third, and fourth eruptions would be $\frac{|79-54|+ |54-74|+ |74-62|}{3} = 19$.


In [38]:
differences = np.abs(np.diff(waiting_times))
average_error = sum(differences) / len(differences / 2)
average_error

20.520295202952031

In [39]:
grader.check("q4_4")

q4_4 results: All test cases passed!

## 5. Tables

**Question 1.** Suppose you have 4 apples, 3 oranges, and 3 pineapples.  (Perhaps you're using Python to solve a high school Algebra problem.)  Create a table that contains this information.  It should have two columns: `fruit name` and `amount`.  Assign the new table to the variable `fruits`. **(4 Points)**

*Note:* Use lower-case and singular words for the name of each fruit, like `"apple"`.


In [40]:
# Our solution uses 1 statement split over 3 lines.
fruits = Table().with_columns(
    "fruit name", ["apple", "orange", "pineapple"],
    "amount", [4, 3, 3]
)
fruits

fruit name | amount
apple      | 4
orange     | 3
pineapple  | 3

In [41]:
grader.check("q5_1")

q5_1 results: All test cases passed!

**Question 2.** The file `inventory.csv` contains information about the inventory at a fruit stand.  Each row represents the contents of one box of fruit. Load it as a table named `inventory` using the `Table.read_table()` function. `Table.read_table(...)` takes one argument (data file name in string format) and returns a table. **(4 Points)**


In [42]:
inventory = Table.read_table("inventory.csv")
inventory

box ID | fruit name | count
53686  | kiwi       | 45
57181  | strawberry | 123
25274  | apple      | 20
48800  | orange     | 35
26187  | strawberry | 255
57930  | grape      | 517
52357  | strawberry | 102
43566  | peach      | 40

In [43]:
grader.check("q5_2")

q5_2 results: All test cases passed!

**Question 3.** Does each box at the fruit stand contain a different fruit? Set `all_different` to `True` if each box contains a different fruit or to `False` if multiple boxes contain the same fruit. **(4 Points)**

*Hint:* You don't have to write code to calculate the True/False value for `all_different`. Just look at the `inventory` table and assign `all_different` to either `True` or `False` according to what you can see from the table in answering the question.


In [44]:
all_different = True
all_different

True

In [45]:
grader.check("q5_3")

q5_3 results: All test cases passed!

**Question 4.** The file `sales.csv` contains the number of fruit sold from each box last Saturday.  It has an extra column called `price per fruit ($)` that's the price *per item of fruit* for fruit in that box.  The rows are in the same order as the `inventory` table.  Load these data into a table called `sales`. **(5 Points)**


In [46]:
sales = Table.read_table("sales.csv")
sales

box ID | fruit name | count sold | price per fruit ($)
53686  | kiwi       | 3          | 0.5
57181  | strawberry | 101        | 0.2
25274  | apple      | 0          | 0.8
48800  | orange     | 35         | 0.6
26187  | strawberry | 25         | 0.15
57930  | grape      | 355        | 0.06
52357  | strawberry | 102        | 0.25
43566  | peach      | 17         | 0.8

In [47]:
grader.check("q5_4")

q5_4 results: All test cases passed!

**Question 5.** How many fruits did the store sell in total on that day? **(5 Points)**


In [48]:
total_fruits_sold = sum(sales.column("count sold"))
total_fruits_sold

638

In [49]:
grader.check("q5_5")

q5_5 results: All test cases passed!

**Question 6.** What was the store's total revenue (the total price of all fruits sold) on that day? **(5 Points)**

*Hint:* If you're stuck, think first about how you would compute the total revenue from just the grape sales.


In [50]:
total_revenue = sum(sales.column("count sold") * sales.column("price per fruit ($)"))
total_revenue

106.84999999999999

In [51]:
grader.check("q5_6")

q5_6 results: All test cases passed!

**Question 7.** Make a new table called `remaining_inventory`.  It should have the same rows and columns as `inventory`, except that the amount of fruit sold from each box should be subtracted from that box's **original** count, so that the `count` column is **updated to be** the amount of fruit remaining after Saturday. **(5 Points)**


In [52]:
remaining_inventory = Table().with_columns(
    "box ID", inventory.column("box ID"),
    "fruit name", inventory.column("fruit name"),
    "count", inventory.column("count") - sales.column("count sold")
)
remaining_inventory

box ID | fruit name | count
53686  | kiwi       | 42
57181  | strawberry | 22
25274  | apple      | 20
48800  | orange     | 0
26187  | strawberry | 230
57930  | grape      | 162
52357  | strawberry | 0
43566  | peach      | 23

In [53]:
grader.check("q5_7")

q5_7 results: All test cases passed!

#### `Good Job! You are done with Homework 2!`

## Submission

After you have completed the assignment, do the following to submit it:

1. **Save** the notebook file (File ==> Save Notebook) (or the Save icon)
2. Go to the notebook menu, choose Kernel ==> **Restart Kernel and Run All Cells**.
3. Make sure everything is fine. 
4. **Save** the notebook file (File ==> Save Notebook)
5. Use the Juypter Notebook dashboard to create a **duplicate** of the file and then **rename** it from hw01.ipynb_copy to **hw02_FIRSTNAME_LASTNAME**.ipynb to be graded. That way you will be able to keep your original file. 
6. **Upload** **hw02_FIRSTNAME_LASTNAME** to Canvas.